openapi: '3.0.0'
info:
  description: myEki apis
  version: 1.0.0
  title: myeki

servers:
  - url: /api
    description: v1 baseUrl

components:
  securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

paths:
  /front/business-industries:
    get:
      security:
        - bearerAuth: []
      tags:
        - Business Listing
      summary: Get the list of business industries
      description: Get the list of business industries
      operationId: GetBusinessindustries
     
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/business-listings:
    get:
      security:
        - bearerAuth: []
      tags:
        - Business Listing
      summary: Get the list of business listings
      description: Get the list of business listings
      operationId: GetBusinessListing
      parameters:
        - in: query
          name: search
          schema:
            type: string
            example: ""
          required: false
        - in: query
          name: industry
          style: form
          explode: false
          schema:
            type: array
            items:
              type: number
              description: Filter by industry
              example: 1
            required: false

      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/business-listings/scrape-site:
    post:
      security:
        - bearerAuth: []
      tags:
        - Business Listing
      summary: Scrable business site for meta information
      description: Scrable business site for meta information
      operationId: BusinessListingScrapeSite
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: number
                  example: 'https://vusithembekwayo.com'
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object


  /front/business-listings/create:
    post:
      security:
        - bearerAuth: []
      tags:
        - Business Listing
      summary: Create Business listing
      description: Create Business listing
      operationId: CreateBusinessListings
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                industry_id:
                  type: number
                  example: 1
                business_name:
                  type: string
                  example: "Logic importer & exporter"
                business_description:
                  type: string
                  example: "Ikeja"
                business_email:
                  type: string
                  example: "ojuyobo@gmail.com"
                secondary_business_email:
                  type: string
                  example: "ojuyobo2@gmail.com"
                business_address:
                  type: string
                  example: "Kings boulevard"
                country_id:
                  type: number
                  example: 1
                state:
                  type: string
                  example: "Fisherman court"
                business_contact_number:
                  type: string
                  example: "+1 (4585) 4521 454"
                secondary_contact_number:
                  type: string
                  example: "+1 (4585) 4521 454"
                website_link:
                  type: string
                  example: "www.google.com"
                owner_name: 
                  type: string
                  example: "Ojuyobo Titus"
                owner_role: 
                  type: string
                  example: "CEO, Director"
                business_logo_url:
                  type: string
                  example: ""
                show_business_description:
                  type: boolean
                  example: true
                show_business_email:
                  type: boolean
                  example: true
                show_business_address:
                  type: boolean
                  example: true
                show_secondary_email:
                  type: boolean
                  example: true
                show_secondary_contact:
                  type: boolean
                  example: true
                show_website_link:
                  type: boolean
                  example: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object
  
  /chats:
    get:
      security:
        - bearerAuth: []
      tags:
        - Messaging
      summary: Get authenticated user conversations
      description: GetAuthenticatedUserConversations
      operationId: GetAuthenticatedUserConversations
      parameters:
        - in: query
          name: name
          schema:
            type: string
            example: ""
          required: false
            
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object
  
  /chats/{uid}/details:
    get:
      security:
        - bearerAuth: []
      tags:
        - Messaging
      summary: Get Chat Details
      description: Get Chat Details
      operationId: GetChatDetails
      parameters:
        - in: path
          name: uid
          schema:
            type: string
            example: 032cd4c0-fb21-4579-9e10-6b23690cd249
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /chats/start-conversation:
    post:
      security:
        - bearerAuth: []
      tags:
        - Messaging
      summary: Start Conversation
      description: Start Conversation
      operationId: StartConversation
      parameters:
        - in: query
          name: convoRoute
          schema:
            type: string
            example: ""
          required: false

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                  example: 1001
                  required: true
                message:
                  type: string
                  example: "Ojuyobo Titus"
                  required: true
                advert_id:
                  type: string
                  example: 1
                listing_id:
                  type: string
                  example: 1
        
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /chats/send-message:
    post:
      security:
        - bearerAuth: []
      tags:
        - Messaging
      summary: Send Message
      description: Send Message
      operationId: SendMessage
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chat_id:
                  type: number
                  example: 1
                  required: true
                message:
                  type: string
                  example: "Ojuyobo Titus"
                  required: true
        
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /chats/{chat}/read:
    put:
      security:
        - bearerAuth: []
      tags:
        - Messaging
      summary: Update chat read time
      description: Update chat read time
      operationId: readReceipt
      parameters:
        - in: path
          name: chat
          schema:
            type: number
            example: 
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object 

  /chats/{chat}/messages:
    get:
      security:
        - bearerAuth: []
      tags:
        - Messaging
      summary: Get chat messages
      description: Get chat messages
      operationId: GetChatMessages
      parameters:

        - in: path
          name: chat
          schema:
            type: number
            example: 
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object 
  
  