openapi: '3.0.0'
info:
  description: Teddyed apis
  version: 1.0.0
  title: Teddyed

servers:
  - url: /api
    description: v1 baseUrl

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:

  /api/front/register:
    post:
      tags:
        - Authentication
      summary: register users step one
      description: register users step one
      operationId: RegisterStepOne
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: 'Teddy'
                last_name:
                  type: string
                  example: 'Edward'
                email:
                  type: string
                  example: 'teddyedward@teddyed.com'
                password:
                  type: string
                  example: 'teddy767112##'
                password_confirmation:
                  type: string
                  example: 'teddy767112##'

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /api/front/register/verify:
    post:
      tags:
        - Authentication
      summary: register users step two verify otp
      description: register users step two verify otp
      operationId: RegisterStepTwo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: 'Teddy'
                last_name:
                  type: string
                  example: 'Edward'
                email:
                  type: string
                  example: 'teddyedward@teddyed.com'
                password:
                  type: string
                  example: 'teddy767112##'
                password_confirmation:
                  type: string
                  example: 'teddy767112##'
                code:
                  type: string
                  example: '123456'

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /api/front/register/otp-resend:
    post:
      tags:
        - Authentication
      summary: register users step two resend otp
      description: register users step two resend otp
      operationId: RegisterStepTwoResend
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'teddyedward@teddyed.com'

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /api/front/login:
    post:
      tags:
        - Authentication
      summary: login users
      description: login users
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userid:
                  type: string
                  example: teddyedward@teddyed.com'
                password:
                  type: string
                  example: '12345678'
      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object
  /api/front/reset/send-otp:
    post:
      tags:
        - Authentication
      summary: send otp to reset password
      description: send otp to reset password
      operationId: sendOtpToResetPassword
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'teddyedward@teddyed.com'
      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object
  /api/front/reset:
    post:
      tags:
        - Authentication
      summary: reset password
      description: reset password
      operationId: resetPassword
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'teddyedward@teddyed.com'
                password:
                  type: string
                  example: '12345678'
                password_confirmation:
                  type: string
                  example: '12345678'
                otp:
                  type: string
                  example: '123456'
      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object
