openapi: '3.0.0'
info:
  description: myEki apis
  version: 1.0.0
  title: myeki

servers:
  - url: /api
    description: v1 baseUrl

components:
  securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

paths:
  /front/cart/add/{product}:
    post:
      tags:
        - Cart
      summary: add product to cart
      description: add product to cart
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: product
          schema:
            type: string
            example: "pounded-yam"
          required: true
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/cart/edit/{product}:
    put:
      tags:
        - Cart
      summary: edit the quantity of a cart
      description: edit the quantity of a cart
      operationId: EditCart
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: product
          schema:
            type: string
            example: "pounded-yam"
          required: true
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
                  required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/cart/remove/{product}:
    delete:
      tags:
        - Cart
      summary: remove product from cart
      description: remove product from cart
      operationId: RemoveCart
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: product
          schema:
            type: string
            example: "pounded-yam"
          required: true
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/cart/clear:
    delete:
      tags:
        - Cart
      summary: clear cart
      description: clear cart
      operationId: ClearCart
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/cart:
    get:
      tags:
        - Cart
      summary: get cart
      description: get cart
      operationId: GetCart
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/user/shipping-address/create:
    post:
      tags:
        - Shipping
      summary: create shipping new address for cart order
      description: create shipping new address for cart order
      operationId: CreateShippingAddress
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                  example: "Ikeja"
                  required: true
                state:
                  type: string
                  example: "Lagos"
                  required: true
                country:
                  type: string
                  example: "Nigeria"
                  required: true
                lga:
                  type: string
                  example: "Ikeja"
                  required: true
                address:
                  type: string
                  example: "2, Ajegunle street"
                  required: true
                landmark:
                  type: string
                  example: ""
                  required: false
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/user/shipping-address:
    get:
      tags:
        - Shipping
      summary: get shipping address
      description: get shipping address
      operationId: GetShippingAddress
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/cart/{cart}/order:
    post:
      tags:
        - Cart
      summary: order cart
      description: order cart
      operationId: OrderCart
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
        - in: path
          name: cart
          schema:
            type: string
            example: "1"
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: "Teddy"
                  required: true
                last_name:
                  type: string
                  example: "Edwardson"
                  required: true
                email:
                  type: string
                  example: "teddyedward@teddyed.com"
                  required: true
                phone:
                  type: string
                  example: "2348012345678"
                  required: true,
                shipping_address_id:
                  type: integer
                  example: 1
                  required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/order:
    get:
      tags:
        - Cart
      summary: get user orders
      description: get user orders also by status (incart, pending, completed)
      operationId: Get user Orders
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
        - in: query
          name: order_status
          schema:
            type: string
            example: "incart"
          required: false
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object
