openapi: '3.0.0'
info:
  description: myEki apis
  version: 1.0.0
  title: myeki

servers:
  - url: /api
    description: v1 baseUrl

components:
  securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

paths:
  /front/cart/add/{product}:
    post:
      tags:
        - Cart
      summary: add product to cart
      description: add product to cart
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: product
          schema:
            type: string
            example: "pounded-yam"
          required: true
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/cart/edit/{product}:
    put:
      tags:
        - Cart
      summary: edit the quantity of a cart
      description: edit the quantity of a cart
      operationId: EditCart
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: product
          schema:
            type: string
            example: "pounded-yam"
          required: true
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
                  required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/cart/remove/{product}:
    delete:
      tags:
        - Cart
      summary: remove product from cart
      description: remove product from cart
      operationId: RemoveCart
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: product
          schema:
            type: string
            example: "pounded-yam"
          required: true
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/cart/clear:
    delete:
      tags:
        - Cart
      summary: clear cart
      description: clear cart
      operationId: ClearCart
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

  /front/cart:
    get:
      tags:
        - Cart
      summary: get cart
      description: get cart
      operationId: GetCart
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: session-uid
          schema:
            type: string
            example:
          required: true
      responses:
        default:
          description: "success"
          content:
            application/json:
              schema:
                type: object

