openapi: '3.0.0'
info:
  description: Teddyed apis
  version: 1.0.0
  title: Teddyed

servers:
  - url: /api
    description: v1 baseUrl

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:

  /store/user-store:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Store
      summary: Get User Store Info
      description: 'Get User Store Info'
      operationId: GetUserStoreTnfo

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/user-store/{userStore}/metrics:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Store
      summary: Get User Store Metrics
      description: 'Get User Store Metrics'
      operationId: GetUserStoreMetrics
      parameters:
        - in: path
          name: userStore
          schema:
            type: string
            example: amala-sky
          required: true
        - in: query
          name: listingType
          schema:
            type: string
            example: product
          required: true
      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/create:
    post:
      security:
        - bearerAuth: []
      tags:
        - User Store
      summary: Create User Store
      description: Create User Store
      operationId: CreateUserStore

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Amala Sky"
                contact_number:
                  type: string
                  example: "1234567898"
                whatsapp_number:
                  type: string
                  example: "1234567890"
                profile_picture_path:
                  type: string
                  example: ""
                banner_path:
                  type: string
                  example: ""
                description:
                  type: string
                  example: "The best amala in ibadan"
                address1:
                  type: string
                  example: "oluyole ibadan"
                address2:
                  type: string
                  example: "Good arena , eleyele ibadan"
                state:
                  type: string
                  example: "oyo"
                city:
                  type: string
                  example: "ibadan"
                postal_code:
                  type: string
                  example: "100001"
                country:
                  type: integer
                  example: 38
                offers_service:
                  type: string
                  example: false
                offers_product:
                  type: string
                  example: true
      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/{userStore}/update:
    patch:
      security:
        - bearerAuth: []
      tags:
        - User Store
      summary: Update User Store
      description:  Update User Store
      operationId: UpdateUserStore
      parameters:
        - in: path
          name: userStore
          schema:
            type: string
            example: amala-sky
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Amala Sky"
                contact_number:
                  type: string
                  example: "1234567898"
                whatsapp_number:
                  type: string
                  example: "1234567890"
                profile_picture_path:
                  type: string
                  example: ""
                banner_path:
                  type: string
                  example: ""
                description:
                  type: string
                  example: "The best amala in ibadan"
                address1:
                  type: string
                  example: "oluyole ibadan"
                address2:
                  type: string
                  example: "Good arena , eleyele ibadan"
                state:
                  type: string
                  example: "oyo"
                city:
                  type: string
                  example: "ibadan"
                postal_code:
                  type: string
                  example: "100001"
                country:
                  type: integer
                  example: 38
      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/{userStore}/listings:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Store Listings
      summary: Get User Store Listings
      description: 'Get User Store Listings'
      operationId: GetUserStoreListings
      parameters:
        - in: path
          name: userStore
          schema:
            type: string
            example: amala-sky
          required: true

        - in: query
          name: listingType
          schema:
            type: string
            example: 'product'
          required: true
        - in: query
          name: availability
          schema:
            type: boolean
            example: true
          required: true

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/{userStore}/listings/create:
    post:
      security:
        - bearerAuth: []
      tags:
        - User Store Listings
      summary: Create User Store Listing
      description: Create User Store Listing
      operationId: CreateUserStoreListing
      parameters:
        - in: path
          name: userStore
          schema:
            type: string
            example: amala-sky
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Amala Full plate"
                type:
                  type: string
                  example: "product"
                price:
                  type: string
                  example: "1000"
                currency:
                  type: string
                  example: "USD"
                  enum: ['USD', 'NGN','CAD']
                description:
                  type: string
                  example: "dnndvs"
                additional_information:
                  type: string
                  example: "fdsgrrwg"
                images:
                  type: array
                  items:
                    type: string
                category:
                  type: number
                  example: 11

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/listings/{userStore}/listing/{listing}:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Store Listings
      summary: Get User Store Listing
      description: 'Get User Store Listing'
      operationId: GetUserStoreListing
      parameters:
        - in: path
          name: userStore
          schema:
            type: string
            example: amala-sky
          required: true
        - in: path
          name: listing
          schema:
            type: string
            example: pounded-yam
          required: true

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/listings/{userStore}/listing/{listing}/set-availability:
    patch:
      security:
        - bearerAuth: []
      tags:
        - User Store Listings
      summary: Set Availability User Store Listing
      description: Set Availability User Store Listing
      operationId: SetAvailabilityUserStoreListing
      parameters:
        - in: path
          name: userStore
          schema:
            type: string
            example: amala-sky
          required: true
        - in: path
          name: listing
          schema:
            type: string
            example: pounded-yam
          required: true

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                is_available:
                  type: number
                  example: 0

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/listings/{userStore}/listing/{listing}/update:
    patch:
      security:
        - bearerAuth: []
      tags:
        - User Store Listings
      summary: Update User Store Listing
      description: Update User Store Listing
      operationId: UpdateUserStoreListing
      parameters:
        - in: path
          name: userStore
          schema:
            type: string
            example: amala-sky
          required: true
        - in: path
          name: listing
          schema:
            type: string
            example: pounded-yam
          required: true

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Amala Full plate"
                type:
                  type: string
                  example: "product"
                price:
                  type: string
                  example: "1000"
                description:
                  type: string
                  example: "dnndvs"
                additional_information:
                  type: string
                  example: "fdsgrrwg"
                images:
                  type: array
                  items:
                    type: string
                category:
                  type: number
                  example: 11

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/listings/{userStore}/listing/{listing}/delete:
     delete:
        security:
          - bearerAuth: []
        tags:
          - User Store Listings
        summary: Delete User Store Listing
        description: 'Delete User Store Listing'
        operationId: DeleteUserStoreListing
        parameters:
          - in: path
            name: userStore
            schema:
              type: string
              example: amala-sky
            required: true
          - in: path
            name: listing
            schema:
              type: string
              example: pounded-yam
            required: true

        responses:
          default:
            description: 'success'
            content:
              application/json:
                schema:
                  type: object


