openapi: '3.0.0'
info:
  description: Teddyed apis
  version: 1.0.0
  title: Teddyed

servers:
  - url: /api
    description: v1 baseUrl

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:

  /store/user-store:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Store
      summary: Get User Store Info
      description: 'Get User Store Info'
      operationId: GetUserStoreTnfo

      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/create:
    post:
      security:
        - bearerAuth: []
      tags:
        - User Store
      summary: Create User Store
      description: Create User Store
      operationId: CreateUserStore

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Amala Sky"
                contact_number:
                  type: string
                  example: "1234567898"
                whatsapp_number:
                  type: string
                  example: "1234567890"
                profile_picture_path:
                  type: string
                  example: "dnndvs"
                banner_path:
                  type: string
                  example: "fdsgrrwg"
                description:
                  type: string
                  example: "The best amala in ibadan"
                address1:
                  type: string
                  example: "oluyole ibadan"
                address2:
                  type: string
                  example: "Good arena , eleyele ibadan"
                state:
                  type: string
                  example: "oyo"
                city:
                  type: string
                  example: "ibadan"
                postal_code:
                  type: string
                  example: "100001"
                offers_service:
                  type: string
                  example: false
                offers_product:
                  type: string
                  example: true
      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object

  /store/{userStore}/update:
    post:
      security:
        - bearerAuth: []
      tags:
        - User Store
      summary: Update User Store
      description:  Update User Store
      operationId: UpdateUserStore
      parameters:
        - in: path
          name: userStore
          schema:
            type: number
            example: 0
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Amala Sky"
                contact_number:
                  type: string
                  example: "1234567898"
                whatsapp_number:
                  type: string
                  example: "1234567890"
                profile_picture_path:
                  type: string
                  example: "ccvv"
                banner_path:
                  type: string
                  example: "srggerv"
                description:
                  type: string
                  example: "The best amala in ibadan"
                address1:
                  type: string
                  example: "oluyole ibadan"
                address2:
                  type: string
                  example: "Good arena , eleyele ibadan"
                state:
                  type: string
                  example: "oyo"
                city:
                  type: string
                  example: "ibadan"
                postal_code:
                  type: string
                  example: "100001"
      responses:
        default:
          description: 'success'
          content:
            application/json:
              schema:
                type: object
