version: '3'
services:
  teddymart-prod:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        PHP_FPM_PORT: 9020 
    container_name: teddymart-prod
    restart: unless-stopped
    ports:
      - "9020:9020"
    volumes:
      - .:/var/www
    networks:
      tednet:
        ipv4_address: 172.24.0.2
networks:
  tednet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24